# Code generated by Grok.
def quick_sort(arr):
    # Base case: lists with 0 or 1 elements are already sorted
    if len(arr) <= 1:
        return arr
    
    # Choose pivot (here, the last element)
    pivot = arr[-1]
    
    # Partition elements into three lists
    left = []    # Elements less than pivot
    middle = []  # Elements equal to pivot
    right = []   # Elements greater than pivot
    
    for x in arr:
        if x < pivot:
            left.append(x)
        elif x == pivot:
            middle.append(x)
        else:
            right.append(x)
    
    # Recursively sort left and right partitions
    return quick_sort(left) + middle + quick_sort(right)
